console.log('####################')
console.log('#                  #')
console.log('#  Run baby, run!  #')
console.log('#                  #')
console.log('####################')

require('./symlink')
require('./cli')
require('./app')
require('./settings')
